### ISSUE TITLE
Cant find a way to use silent authentication

### ISSUE THREAD

**Issue by casberkman1** [madeITBelgium/TeamLeader#10]
Is it possible to silent authenticate so im not prompted with a login screen to enter my credentials?

Thanks in advance!

**Comment by madeITBelgium** [comment]
Hi, It is not possible to log in without the login screen. You have to do that once.

When your access token is invalid you can request a new one without the login screen. So you only have to do the login screen once.

```
TeamLeader::setAccessToken($access_token);
TeamLeader::setRefreshToken($refresh_token);
TeamLeader::setExpiresAt($expired_at);
$refresh = TeamLeader::checkAndDoRefresh();
if (false !== $refresh) {
    $access_token = TeamLeader::getAccessToken();
    $refresh_token = TeamLeader::getRefreshToken();
    $expired_at = TeamLeader::getExpiresAt();
    //Save data to database
}
```
