### ISSUE TITLE
Add compagnies endpoint ?

### ISSUE THREAD

**Issue by DonDiegoAA** [madeITBelgium/TeamLeader#9]
Hello,

I need to communicate with TeamLeader from my Laravel application.
This package seems to be perfectly suited for me, I will quickly test it.
But I see that the endpoint companies are not currently integrated, and I will need it.
Is there a chance that you will add them soon?
Otherwise I will fork and try to add them myself.

Thank you

**Comment by madeITBelgium** [comment]
If you can, you may try to add it and do a pull request. Otherwise, I will try to add it in the next few days.

**Comment by madeITBelgium** [comment]
#16 & #17 adds companies endpoint.
